### ISSUE TITLE
filter matching unexpected text

### ISSUE THREAD

**Issue by TBog** [aranhil/qgrepGUI#113]
# Description #
When we have group by file matching the filter text in the file name is unexpected.

## Expected behavior ##
Filter text should be highlighted in the result. 

### Screenshots ###
![image](https://github.com/aranhil/qgrepGUI/assets/6465804/f20d7e47-f4e6-4b88-9db7-d831981bc2e4)

**Comment by flalexp** [comment]
Maybe the filter should work only on search results, ignoring paths ?

**Comment by aranhil** [comment]
It's exactly what Visual Studio does:
![image](https://github.com/aranhil/qgrepGUI/assets/755601/c4b9651b-e603-4159-b53e-cf56fd72b120)
And they don't highlight the filter text

**Comment by TBog** [comment]
But you already have the "Include file" field for that, VS does not.

**Comment by aranhil** [comment]
I'd rather add an option than limit existing functionality.
