### ISSUE TITLE
Auto-update index

### ISSUE THREAD

**Issue by TBog** [aranhil/qgrepGUI#114]
**Description**
I sometimes find myself not finding the text I just wrote and I need to do a manual "Update index"

**Solution**
I've seen a [watcher](https://stackoverflow.com/questions/760904/how-can-i-monitor-a-windows-directory-for-changes) that could help.

**Alternative solutions**
Do an update with a time interval.

**Comment by aranhil** [comment]
![image](https://github.com/aranhil/qgrepGUI/assets/755601/af8fbbd3-877c-4bcd-b959-0862389fd2f6)
