### ISSUE TITLE
Grouped results reset while searching

### ISSUE THREAD

**Issue by TBog** [aranhil/qgrepGUI#115]
# Description #
While the search in ongoing if I open grouped results the selection keeps resetting

## Context ##
I was looking for something pretty common and it took some time for the results to finish loading.
I have group by file enabled

## Steps to Reproduce ##
1. open `qgrep Search Tool` in a big project
2. type `int`
3. press down arrow key to select first result
4. press right arrow key to expand
5. See how the group keeps collapsing immediately after if the search is not finished

## Expected behavior ##
Once expanded I expect the group to remain expanded until I collapse it.

**Comment by aranhil** [comment]
I'll look into it.
