### ISSUE TITLE
Open File dialog should retain it's size between uses

### ISSUE THREAD

**Issue by flalexp** [aranhil/qgrepGUI#116]
**Description**

Right now the Open File dialog seems to have a fixed size when it's displayed. Even if the user will resize it, after closing and opening it again the dialog has the same fixed size as before. 

It would be nice for the Open File dialog to "remember" the user set size. It's useful for instance, when using long file paths and the user might increase the width of the window when doing a file search.

**Comment by aranhil** [comment]
They all should
