### ISSUE TITLE
Option for Open File to search only in file names, no matter what path style is set

### ISSUE THREAD

**Issue by flalexp** [aranhil/qgrepGUI#117]
**Description**
When qgrep is configured with absolute or relative path styles, the Open File dialog may display results that match portions of the file path, even if the file name has nothing to do with the search criteria. 

![image](https://github.com/aranhil/qgrepGUI/assets/11877397/a91c553a-fc17-4fe4-a1ce-4dabf5828d7d)

I think most of the time people want to use the file name for searches, independent of the path style used.

**Solution**
Make Open File use only file names, or add an option for it

**Comment by aranhil** [comment]
I'd rather add an option than limit existing functionality.
