### ISSUE TITLE
Add option to disable automatic index refresh (for manual refresh)

### ISSUE THREAD

**Issue by flalexp** [aranhil/qgrepGUI#8]
I personally use manual refresh. I would like to be able to disable the automatic refresh in a more nicely manner (checkbox ?), rather than set a very big number for the refresh rate

**Comment by TBog** [comment]
Can you keep the automatic refresh and only trigger it when files changed? I've seen a [watcher](https://stackoverflow.com/questions/760904/how-can-i-monitor-a-windows-directory-for-changes) that could maybe help.
